export const PRACTICE_OPTIONS = [
    "Civil Litigation",
    "Small Claims",
    "Administrative Law",
    "Employment and Labour",
    "Human Rights",
    "Residential Tenancies",
    "Family",
    "Criminal",
    "Estates",
    "Corporate and Commercial",
    "Privacy",
    "Intellectual Property",
    "Entertainment and Media",
    "Municipal",
    "Professional Regulation",
    "Bankruptcy and Insolvency",
    "Immigration",
    "General Transactions",
    "Corporate",
    "Finance",
    "Litigation",
    "Real Estate",
    "Tax",
    "Employment",
    "IP",
    "Competition",
    "Tech Transactions",
    "Project Finance",
    "EC/VC",
    "Private Equity",
    "Private Credit",
    "ECM",
    "DCM",
    "Lev Fin",
    "Arbitration",
    "Other",
] as const;

export type Practice = (typeof PRACTICE_OPTIONS)[number];
