-- ROSS-120: immutable audit records for official Ontario procedure-source
-- metadata checks. Source text and court forms are not copied into this table.

create table if not exists public.legal_source_version_checks (
  id bigint generated by default as identity primary key,
  source_id text not null,
  source_url text not null,
  checked_at timestamptz not null,
  reachable boolean not null,
  etag text,
  last_modified text,
  metadata_hash text not null,
  created_at timestamptz not null default now(),
  constraint legal_source_version_checks_metadata_hash_format
    check (metadata_hash ~ '^[a-f0-9]{64}$'),
  constraint legal_source_version_checks_source_metadata_unique
    unique (source_id, metadata_hash)
);

alter table public.legal_source_version_checks enable row level security;

-- Checks are written and read only by the backend service role. No browser
-- grant or permissive RLS policy is intentionally created.
revoke all on table public.legal_source_version_checks from anon, authenticated;
