// Shared env stub for DMS tests whose import graph reaches lib/env (via
// lib/storage / documents.upload). Mirrors the zod defaults in lib/env.ts so
// the modules under test see a fully-populated, network-free config.
export const fakeEnv = {
    SUPABASE_URL: "http://localhost:54321",
    SUPABASE_SECRET_KEY: "test-secret-key",
    DOWNLOAD_SIGNING_SECRET: "x".repeat(32),
    USER_API_KEYS_ENCRYPTION_SECRET: "y".repeat(32),
    PORT: 3001,
    NODE_ENV: "test" as const,
    FRONTEND_URL: "http://localhost:3000",
    TRUST_PROXY_HOPS: 1,
    RATE_LIMIT_GENERAL_WINDOW_MINUTES: 15,
    RATE_LIMIT_GENERAL_MAX: 300,
    RATE_LIMIT_CHAT_WINDOW_MINUTES: 15,
    RATE_LIMIT_CHAT_MAX: 30,
    RATE_LIMIT_CHAT_CREATE_WINDOW_MINUTES: 15,
    RATE_LIMIT_CHAT_CREATE_MAX: 60,
    RATE_LIMIT_UPLOAD_WINDOW_HOURS: 1,
    RATE_LIMIT_UPLOAD_MAX: 50,
    R2_BUCKET_NAME: "mike",
    R2_REGION: "auto",
    GCS_BUCKET_NAME: "mike",
    GCS_SIGNED_URL_TTL: 3600,
    VERTEX_AI_LOCATION: "us-central1",
    OPENAI_ALLOW_LOCAL_BASE_URL: "false" as const,
    ENABLE_OLLAMA: "false" as const,
    AIRGAPPED: "false" as const,
    CREDITS_FAIL_CLOSED: "false" as const,
    REDIS_URL: "redis://localhost:6379",
    ASYNC_DOCUMENT_CONVERSION: "false" as const,
    ASYNC_TABULAR_EXTRACTION: "false" as const,
    ASYNC_EMBEDDING: "false" as const,
    EMBEDDING_DIMENSION: 768,
    SENTRY_TRACES_SAMPLE_RATE: 0,
};
